### ISSUE TITLE
小程序里this.$vm.$mp.query 报错的问题

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#1889]
**问题描述**
在微信小程序 如果在main.js里面将app.$mount()延迟执行的话，就会报错，具体代码：
```javascript
async initApp() {
    await fetchData();
    const app = new Vue({
        store,
        ...App
    });

    app.$mount();
}

initApp();
```

**Comment by fxy060608** [comment]
不支持异步mount

**Comment by lucyG18** [comment]
这个怎么解决

**Comment by lucyG18** [comment]
这个怎么解决

**Comment by GitHubwyq** [comment]
> 不支持异步mou

> 不支持异步mount

那如果我想增加一个入口的配置数据，我应该怎么处理呢

**Comment by pengziyun** [comment]
已经解决了？有同样的问题，求解

**Comment by GitHubwyq** [comment]
我这边报这个错误是应为我在小程序端异步挂载vue实例引起的（翻了uni-app的文档以及issue，得到的回答是uni-app不支持异步挂载实例，但是H5端异步挂载实例是没问题的），目前我这边的解决方案是写了个条件编译


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 小程序里this.$vm.$mp.query 报错的问题 (#1889)





 
已经解决了？有同样的问题，求解
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imaxing** [comment]
这么写我遇到同样的问题

<img width="513" alt="image" src="https://user-images.githubusercontent.com/26427785/192182529-5ebf3a5f-d6ca-4c84-b0bd-c4da07e3b882.png">
